export type MessageCode =
  | "UNKNOWN_ERROR"
  | "VALIDATION_ERROR"
  | "VALIDATION_GENERAL_PARAM_ERROR"
  | "DATA_ACCESS_ERROR"
  | "UNAUTHORIZED_ERROR"
  | "AI_MESSAGE_TOO_LARGE"
  | "AI_API_ERROR"
  // ユーザ管理ドメインバリデーションエラー
  | "USER_ID_INVALID_FORMAT"
  | "EMPLOYEE_ID_EMPTY"
  | "EMPLOYEE_ID_TOO_LONG"
  | "DISPLAY_NAME_EMPTY"
  // 認証エラー
  | "USER_SYNC_FAILED";
